// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXUR0We1Fad-QhHTyjbMh5iaFm38mNBII',
    appId: '1:330744362982:web:27aeee6c58d9152f510827',
    messagingSenderId: '330744362982',
    projectId: 'nextspotglobal',
    authDomain: 'nextspotglobal.firebaseapp.com',
    storageBucket: 'nextspotglobal.firebasestorage.app',
    measurementId: 'G-3VJBFQBD6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAInHC7N9ql_UzEaQOUILaHX_tgoRQAMig',
    appId: '1:330744362982:android:eec7d95ec7917e56510827',
    messagingSenderId: '330744362982',
    projectId: 'nextspotglobal',
    storageBucket: 'nextspotglobal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNXdGkHonyAk7ZRPvTVOisfPfQILBIeUI',
    appId: '1:330744362982:ios:68a1973fa57bfa11510827',
    messagingSenderId: '330744362982',
    projectId: 'nextspotglobal',
    storageBucket: 'nextspotglobal.firebasestorage.app',
    androidClientId: '330744362982-hfpcgv70pcpg9df05n2c4ogiv4erjjh7.apps.googleusercontent.com',
    iosClientId: '330744362982-8q6ea385ikuk0o634l72c316igm1pk9t.apps.googleusercontent.com',
    iosBundleId: 'nextspot.co.nextspotAdminpanel',
  );
}
